### PR TITLE
elvis reddit bomb aww

### PR DESCRIPTION
**Pull request by dpritchett**
image

### CODE REVIEW

**Comment by unstablereality** [comment]
Not a bad idea, but reddit being reddit, at the very least this should be restricted to SFW subs, if not a predetermined group of approved subreddits.

**Comment by vongrippen** [comment]
I'm concerned about 2 things with this one:

1. whitelist safe subreddits, because OH GOD NOT r/spacedicks
2. concern for how easy it would be to spam a channel into oblivion

**Comment by vongrippen** [comment]
Wait. Wow. Github _just_ notificed me of this PR... in 2018

**Comment by dpritchett** [comment]
I don't remember what I was thinking back in 2015, let's close it 😬

**Pull request closed without merging**
